name: Build and Release aigit

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          BINARY_NAME=aigit_${{ matrix.os }}_${{ matrix.arch }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            BINARY_NAME+=".exe"
          fi
          go build -ldflags="-s -w" -o $BINARY_NAME main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aigit-${{ matrix.os }}-${{ matrix.arch }}
          path: aigit*
          compression-level: 0

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
          
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/aigit_darwin_amd64
            artifacts/aigit_darwin_arm64
            artifacts/aigit_windows_amd64.exe
