name: Build and Release aigit

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          BINARY_NAME=aigit_${{ matrix.os }}_${{ matrix.arch }}
          if [ "${{ matrix.os }}" == "windows" ]; then
            BINARY_NAME+=".exe"
          fi
          go build -ldflags "-s -w -X main.Version=${VERSION}" -o $BINARY_NAME main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aigit-${{ matrix.os }}-${{ matrix.arch }}
          path: aigit*
          compression-level: 0

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
          
      # First, generate the release notes
      - name: Draft Release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Then, update the release with binary files
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/aigit_darwin_amd64
            artifacts/aigit_darwin_arm64
            artifacts/aigit_windows_amd64.exe
          draft: false
          body: ${{ steps.release_drafter.outputs.body }}
          tag_name: ${{ steps.release_drafter.outputs.tag_name }}
          name: ${{ steps.release_drafter.outputs.name }}
